# Cold Brew

[colors.primary]
background = '#0e1314'
foreground = '#d8e4e0'

[colors.normal]
black   = '#262c2c'
red     = '#d86a58'
green   = '#86b080'
yellow  = '#d2b068'
blue    = '#6a9cb8'
magenta = '#a880a0'
cyan    = '#5cb8b0'
white   = '#bccac4'

[colors.bright]
black   = '#636b6a'
red     = '#e18b7d'
green   = '#a1c19c'
yellow  = '#dcc189'
blue    = '#8bb2c8'
magenta = '#bb9cb5'
cyan    = '#80c8c1'
white   = '#e4eae7'

# --- derivado de la paleta (enrich.py) ---
[colors.cursor]
text = '#0e1314'
cursor = '#5cb8b0'

[colors.vi_mode_cursor]
text = '#0e1314'
cursor = '#80c8c1'

[colors.selection]
text = '#d8e4e0'
background = '#2c524f'

[colors.search.matches]
foreground = '#0e1314'
background = '#dcc189'

[colors.search.focused_match]
foreground = '#0e1314'
background = '#e18b7d'

[colors.footer_bar]
foreground = '#d8e4e0'
background = '#323939'

[colors.hints.start]
foreground = '#0e1314'
background = '#dcc189'

[colors.hints.end]
foreground = '#0e1314'
background = '#8bb2c8'
