# Elden Ring (inspired)

[colors.primary]
background = '#0f0d0a'
foreground = '#e8dcc0'

[colors.normal]
black   = '#1f1b14'
red     = '#d9593f'
green   = '#8aa860'
yellow  = '#e6c065'
blue    = '#6a8ec0'
magenta = '#a878b8'
cyan    = '#62b0a8'
white   = '#c8bca0'

[colors.bright]
black   = '#6a604a'
red     = '#ee826a'
green   = '#aac882'
yellow  = '#f5d88a'
blue    = '#92b0dc'
magenta = '#c49ad0'
cyan    = '#8ccdc4'
white   = '#fff4d8'

# --- derivado de la paleta (enrich.py) ---
[colors.cursor]
text = '#0f0d0a'
cursor = '#e6c065'

[colors.vi_mode_cursor]
text = '#0f0d0a'
cursor = '#8ccdc4'

[colors.selection]
text = '#e8dcc0'
background = '#61512d'

[colors.search.matches]
foreground = '#0f0d0a'
background = '#f5d88a'

[colors.search.focused_match]
foreground = '#0f0d0a'
background = '#ee826a'

[colors.footer_bar]
foreground = '#e8dcc0'
background = '#36322b'

[colors.hints.start]
foreground = '#0f0d0a'
background = '#f5d88a'

[colors.hints.end]
foreground = '#0f0d0a'
background = '#92b0dc'
