# Iceberg

[colors.primary]
background = '#161821'
foreground = '#c6c8d1'

[colors.normal]
black   = '#1e2132'
red     = '#e27878'
green   = '#b4be82'
yellow  = '#e2a478'
blue    = '#84a0c6'
magenta = '#a093c7'
cyan    = '#89b8c2'
white   = '#c6c8d1'

[colors.bright]
black   = '#6b7089'
red     = '#e98989'
green   = '#c0ca8e'
yellow  = '#e9b189'
blue    = '#91acd1'
magenta = '#ada0d3'
cyan    = '#95c4ce'
white   = '#d2d4de'

# --- derivado de la paleta (enrich.py) ---
[colors.cursor]
text = '#161821'
cursor = '#c6c8d1'

[colors.vi_mode_cursor]
text = '#161821'
cursor = '#95c4ce'

[colors.selection]
text = '#c6c8d1'
background = '#455064'

[colors.search.matches]
foreground = '#161821'
background = '#e9b189'

[colors.search.focused_match]
foreground = '#161821'
background = '#e98989'

[colors.footer_bar]
foreground = '#c6c8d1'
background = '#363841'

[colors.hints.start]
foreground = '#161821'
background = '#e9b189'

[colors.hints.end]
foreground = '#161821'
background = '#91acd1'
