# Material Palenight

[colors.primary]
background = '#292d3e'
foreground = '#a6accd'

[colors.normal]
black   = '#292d3e'
red     = '#f07178'
green   = '#c3e88d'
yellow  = '#ffcb6b'
blue    = '#82aaff'
magenta = '#c792ea'
cyan    = '#89ddff'
white   = '#d0d0d0'

[colors.bright]
black   = '#7580ad'
red     = '#ff8b92'
green   = '#ddffa7'
yellow  = '#ffe585'
blue    = '#9cc4ff'
magenta = '#e1acff'
cyan    = '#a3f7ff'
white   = '#ffffff'

# --- derivado de la paleta (enrich.py) ---
[colors.cursor]
text = '#292d3e'
cursor = '#a6accd'

[colors.vi_mode_cursor]
text = '#292d3e'
cursor = '#a3f7ff'

[colors.selection]
text = '#a6accd'
background = '#363e53'

[colors.search.matches]
foreground = '#292d3e'
background = '#ffe585'

[colors.search.focused_match]
foreground = '#292d3e'
background = '#ff8b92'

[colors.footer_bar]
foreground = '#a6accd'
background = '#404458'

[colors.hints.start]
foreground = '#292d3e'
background = '#ffe585'

[colors.hints.end]
foreground = '#292d3e'
background = '#9cc4ff'
