# Tokyo Night Moon

[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

[colors.normal]
black   = '#1b1d2b'
red     = '#ff757f'
green   = '#c3e88d'
yellow  = '#ffc777'
blue    = '#82aaff'
magenta = '#c099ff'
cyan    = '#86e1fc'
white   = '#828bb8'

[colors.bright]
black   = '#636da6'
red     = '#ff8d94'
green   = '#c7fb6d'
yellow  = '#ffd8ab'
blue    = '#9ab8ff'
magenta = '#caabff'
cyan    = '#b2ebff'
white   = '#c8d3f5'

# --- derivado de la paleta (enrich.py) ---
[colors.cursor]
text = '#222436'
cursor = '#c8d3f5'

[colors.vi_mode_cursor]
text = '#222436'
cursor = '#b2ebff'

[colors.selection]
text = '#c8d3f5'
background = '#4c587c'

[colors.search.matches]
foreground = '#222436'
background = '#ffd8ab'

[colors.search.focused_match]
foreground = '#222436'
background = '#ff8d94'

[colors.footer_bar]
foreground = '#c8d3f5'
background = '#404458'

[colors.hints.start]
foreground = '#222436'
background = '#ffd8ab'

[colors.hints.end]
foreground = '#222436'
background = '#9ab8ff'
